backend:
  name: github
  repo: ewddigital-jpg/seoreinigung
  branch: main
  auth_type: pkce
  app_id: Ov23likqSPjBdBGG6qME

locale: de
media_folder: "."
public_folder: "/"

collections:
  - name: "seiten"
    label: "Seiten"
    files:
      - name: "index"
        label: "Startseite"
        file: "index.html"
        fields:
          - {label: "Inhalt", name: "body", widget: "text"}
      - name: "leistungen"
        label: "Leistungen"
        file: "leistungen.html"
        fields:
          - {label: "Inhalt", name: "body", widget: "text"}
      - name: "kontakt"
        label: "Kontakt"
        file: "kontakt.html"
        fields:
          - {label: "Inhalt", name: "body", widget: "text"}
      - name: "ueber-uns"
        label: "Ueber uns"
        file: "ueber-uns.html"
        fields:
          - {label: "Inhalt", name: "body", widget: "text"}
      - name: "faq"
        label: "FAQ"
        file: "faq.html"
        fields:
          - {label: "Inhalt", name: "body", widget: "text"}
